name: qr_biometrics_app
description: Flutter Test for Seek
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  go_router: ^14.8.1
  intl: ^0.19.0
  slang: ^4.5.0
  slang_flutter: ^4.5.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  pigeon: ^25.0.0
  slang_build_runner: ^4.5.0
  very_good_analysis: ^7.0.0

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/


